### ISSUE TITLE
MediaCodec Async Callback is not occurring if other thread has blocking wait.

### ISSUE THREAD

**Issue by khyati0502** [mstorsjo/android-decodeencodetest#2]
I am using MediaCodec OnAsyncInputAvailable and OnAsyncOutputAvailable callbacks introduced in API 28 on native side.
void OnAsyncInputAvailable(
    AMediaCodec *codec,
    void *userdata,
    int32_t index)
{
    CallbackData* callbackData = (CallbackData *) (userdata);
    callbackData->addInputBufferId(index);
}

void OnAsyncOutputAvailable(
    AMediaCodec *codec,
    void *userdata,
    int32_t index,
    AMediaCodecBufferInfo *bufferInfo)
{
    CallbackData* callbackData = (CallbackData *) (userdata);
    callbackData->addOutputBuffer(index, bufferInfo);
}

In my application i have created a queue, in which indexes of available buffers are entered when callback is triggered on native thread. If other thread which Pop from this queue do a blocking wait, then i can see that call from NDK is not coming. One thread is waiting to Pop the element , as queue is empty (it is doing conditional wait , infinite timeout), on the other end Native thread is waiting for the callback to trigger. So application goes in hang state. Is this known issue with native API's? Or am i missing any thing to handle? What needs from application side to get async callback's triggered except to set AMediaCodec_setAsyncNotifyCallback while configuring decoder?

**Comment by mstorsjo** [comment]
> If other thread which Pop from this queue do a blocking wait, then i can see that call from NDK is not coming.

I presume that you are saying that the callback does come if you don't do this blocking pop?

> on the other end Native thread is waiting for the callback to trigger

What does it do when waiting here?

My main guess is that you are blocking the same thread that would do the callback - are you doing the blocking pop or the "waiting for the callback to trigger" on potentially the same thread as the callback will be delivered on?

In any case, this repo isn't a generic help forum and I don't have experience with native async mode, so if the above didn't help, please post the question on stackoverflow.

**Comment by khyati0502** [comment]
> I presume that you are saying that the callback does come if you don't do this blocking pop?
 **Yes Callback comes if i do not wait and return immediately saying no element in queue**

> > on the other end Native thread is waiting for the callback to trigger
> 
> What does it do when waiting here?
>  **I can see Java looper thread waiting for callback to occur** 
> My main guess is that you are blocking the same thread that would do the callback - are you doing the blocking pop or the "waiting for the callback to trigger" on potentially the same thread as the callback will be delivered on?
> **My whole program is running on one thread while callbacks occur on native threads which is different from my thread**
> In any case, this repo isn't a generic help forum and I don't have experience with native async mode, so if the above didn't help, please post the question on stackoverflow.

**Already posted :https://stackoverflow.com/questions/55302242/mediacodec-async-callback-is-not-occurring-if-other-thread-has-blocking-wait**

**Comment by khyati0502** [comment]
@mstorsjo I need some help in using async callbacks from native side can you please guide.
What I am doing : 
Thread 1 :  Initialisation of decoder -> Set Notify Callback -> Configure decoder ->Start Decoder.
   Now same thread is waiting for index to get available so that Input can be copied to it. If index present in queue and encoded data is entered then wait for output buffer index is performed in order to get decoded output frame . All these steps are on same thread.

NDK Thread: On Which calls to OnAsyncInputAvailable , OnAsyncOutputAvailable are done which add indexes to input and output queues respectively.

Problem i am facing: If i do blocking wait in taking indexes from queue , application hangs even NDK thread is not triggering callbacks to put buffer index in queue.

Should i create some other thread ? If yes what task should be assigned to it.

**Comment by mstorsjo** [comment]
Like I said before, I don't have experience with the native version of MediaCodec in combination with the async API, so I do not know the answer beforehand. Thefore I cannot help you unless you post a full example which I can compile and run and debug without spending extra time to build that myself. And I still don't provide random help to people on a random github repo of mine.

Extend your stackoverflow question to a form so that others actually can reproduce what you are doing. If you do that, I or someone else might answer it there. This is the last reply from me on this issue here on github.
